Check arch and os version before installing flightaware-apt-repository and use rm_conffile from dpkgconffilehandling

diff --git a/debian/flightaware-apt-repository.postinst b/debian/flightaware-apt-repository.postinst
--- a/debian/flightaware-apt-repository.postinst
+++ b/debian/flightaware-apt-repository.postinst
@@ -17,15 +17,65 @@ set -e
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
+rm_conffile() {
+    local PKGNAME="$1"
+    local CONFFILE="$2"
+
+    [ -e "$CONFFILE" ] || return 0
+
+    local md5sum="$(md5sum $CONFFILE | sed -e 's/ .*//')"
+    local old_md5sum="$(dpkg-query -W -f='${Conffiles}' $PKGNAME | \
+            sed -n -e "\' $CONFFILE ' { s/ obsolete$//; s/.* //; p }")"
+    if [ "$md5sum" != "$old_md5sum" ]; then
+        echo "Obsolete conffile $CONFFILE has been modified by you."
+        echo "Saving as $CONFFILE.dpkg-bak ..."
+        mv -f "$CONFFILE" "$CONFFILE".dpkg-bak
+    else
+        echo "Removing obsolete conffile $CONFFILE ..."
+        rm -f "$CONFFILE"
+    fi
+}
+
 case "$1" in
     configure)
-        SOURCES_FILE="/etc/apt/sources.list.d/flightaware-apt-repository.list"
-        if [ ! -f $SOURCES_FILE ]
+
+        # Check OS version
+        . '/etc/os-release'
+        case $VERSION_CODENAME in
+            stretch|buster|bullseye)
+                ;;
+            *)
+                echo "Unsupported OS version: $VERSION_CODENAME"
+                exit 1
+                ;;
+        esac
+
+        # Check architecture
+        arch=$( uname -m )
+        case $arch in
+            armv6l|armv7l)
+                ;;
+            *)
+                echo "Unsupported machine architecture: $arch"
+                exit 1
+                ;;
+        esac
+
+        # Cleanup deprecated sources.list from piaware-repository if present
+        listfile="/etc/apt/sources.list.d/piaware-$VERSION_CODENAME.list"
+        rm_conffile piaware-repository $listfile
+
+        # Generate flightaware-apt-repository.list if it doesn't already exist
+        sources_file="/etc/apt/sources.list.d/flightaware-apt-repository.list"
+        if [ ! -f $sources_file ]
         then
-            . '/etc/os-release'
-            SOURCES_FILE_CONTENT="deb http://flightaware.com/adsb/piaware/files/packages $VERSION_CODENAME piaware"
+            sources_file_content="deb http://flightaware.com/adsb/piaware/files/packages $VERSION_CODENAME piaware"
             echo "Adding APT repo configuration for PiAware $VERSION_CODENAME packages"
-            echo $SOURCES_FILE_CONTENT > $SOURCES_FILE
+            cat > $sources_file << EOF
+# This file is automatically generated by the flightaware-apt-repository package
+# to point to the correct FlightAware repository for the currently installed Debian OS.
+$sources_file_content
+EOF
         fi
     ;;
 
